name:                trumat

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Weverything
- -Werror
- -Wno-unsafe
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-missing-kind-signatures
- -Wno-missing-local-signatures
- -Wno-missing-signatures
- -Wno-missing-exported-signatures

library:
  source-dirs: src
  dependencies:
    - text
    - megaparsec
    - containers
    - bytestring

default-extensions:
  - OverloadedStrings

executables:
  trumat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - directory
    - text
    - bytestring

tests:
  trumat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - tasty
    - tasty-hunit
    - text
