name:                trumat
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings

ghc-options:
- -Weverything
- -Werror
- -Wno-safe
- -Wno-prepositive-qualified-module
- -Wno-missing-safe-haskell-mode
- -Wno-unsafe
- -Wno-monomorphism-restriction
- -Wno-missing-import-lists
- -Wno-missing-kind-signatures
- -Wno-missing-deriving-strategies
- -Wno-missed-specialisations
- -Wno-unused-matches
- -Wno-implicit-prelude
- -O2

library:
  source-dirs: src
  dependencies:
  - text

executables:
  trumat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - bytestring
    - text
    - directory

tests:
  trumat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - tasty
    - tasty-hunit
    - text
