name:                trumat
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

ghc-options:
- -Weverything
- -Werror
- -Wno-safe
- -Wno-prepositive-qualified-module
- -Wno-missing-safe-haskell-mode
- -Wno-unsafe
- -Wno-monomorphism-restriction

library:
  source-dirs: src
  dependencies:
  - text

executables:
  trumat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat

tests:
  trumat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - tasty
    - tasty-hunit
    - text
