name:                trumat

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Werror
- -Weverything

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - text

executables:
  trumat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat

tests:
  trumat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - tasty-hunit
    - tasty
    - text
