name:                trumat

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Werror
- -Weverything
- -Wno-safe
- -Wno-missing-kind-signatures
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-missing-deriving-strategies
- -Wno-unsafe
- -Wno-type-defaults

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - text

executables:
  trumat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat

tests:
  trumat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trumat
    - tasty-hunit
    - tasty
