-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.TextMatchHighlight exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The indice in the fragment where the matched text begins.
-}
beginIndice : SelectionSet Int GithubNoFormat.Object.TextMatchHighlight
beginIndice =
    Object.selectionForField "Int" "beginIndice" [] Decode.int


{-| The indice in the fragment where the matched text ends.
-}
endIndice : SelectionSet Int GithubNoFormat.Object.TextMatchHighlight
endIndice =
    Object.selectionForField "Int" "endIndice" [] Decode.int


{-| The text matched.
-}
text : SelectionSet String GithubNoFormat.Object.TextMatchHighlight
text =
    Object.selectionForField "String" "text" [] Decode.string
