-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.CodeOfConduct exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The body of the CoC
-}
body : SelectionSet (Maybe String) GithubNoFormat.Object.CodeOfConduct
body =
    Object.selectionForField "(Maybe String)" "body" [] (Decode.string |> Decode.nullable)


{-| The key for the CoC
-}
key : SelectionSet String GithubNoFormat.Object.CodeOfConduct
key =
    Object.selectionForField "String" "key" [] Decode.string


{-| The formal name of the CoC
-}
name : SelectionSet String GithubNoFormat.Object.CodeOfConduct
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The path to the CoC
-}
url : SelectionSet (Maybe GithubNoFormat.ScalarCodecs.Uri) GithubNoFormat.Object.CodeOfConduct
url =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "url" [] (GithubNoFormat.ScalarCodecs.codecs |> GithubNoFormat.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
