-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.RenamedTitleEvent exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the actor who performed the event.
-}
actor :
    SelectionSet decodesTo GithubNoFormat.Interface.Actor
    -> SelectionSet (Maybe decodesTo) GithubNoFormat.Object.RenamedTitleEvent
actor object____ =
    Object.selectionForCompositeField "actor" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet GithubNoFormat.ScalarCodecs.DateTime GithubNoFormat.Object.RenamedTitleEvent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (GithubNoFormat.ScalarCodecs.codecs |> GithubNoFormat.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the current title of the issue or pull request.
-}
currentTitle : SelectionSet String GithubNoFormat.Object.RenamedTitleEvent
currentTitle =
    Object.selectionForField "String" "currentTitle" [] Decode.string


id : SelectionSet GithubNoFormat.ScalarCodecs.Id GithubNoFormat.Object.RenamedTitleEvent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GithubNoFormat.ScalarCodecs.codecs |> GithubNoFormat.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Identifies the previous title of the issue or pull request.
-}
previousTitle : SelectionSet String GithubNoFormat.Object.RenamedTitleEvent
previousTitle =
    Object.selectionForField "String" "previousTitle" [] Decode.string


{-| Subject that was renamed.
-}
subject :
    SelectionSet decodesTo GithubNoFormat.Union.RenamedTitleSubject
    -> SelectionSet decodesTo GithubNoFormat.Object.RenamedTitleEvent
subject object____ =
    Object.selectionForCompositeField "subject" [] object____ Basics.identity
