-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.AddCommentPayload exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) GithubNoFormat.Object.AddCommentPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The edge from the subject's comment connection.
-}
commentEdge :
    SelectionSet decodesTo GithubNoFormat.Object.IssueCommentEdge
    -> SelectionSet decodesTo GithubNoFormat.Object.AddCommentPayload
commentEdge object____ =
    Object.selectionForCompositeField "commentEdge" [] object____ Basics.identity


{-| The subject
-}
subject :
    SelectionSet decodesTo GithubNoFormat.Interface.Node
    -> SelectionSet decodesTo GithubNoFormat.Object.AddCommentPayload
subject object____ =
    Object.selectionForCompositeField "subject" [] object____ Basics.identity


{-| The edge from the subject's timeline connection.
-}
timelineEdge :
    SelectionSet decodesTo GithubNoFormat.Object.IssueTimelineItemEdge
    -> SelectionSet decodesTo GithubNoFormat.Object.AddCommentPayload
timelineEdge object____ =
    Object.selectionForCompositeField "timelineEdge" [] object____ Basics.identity
