-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.DeleteProjectCardPayload exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) GithubNoFormat.Object.DeleteProjectCardPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The column the deleted card was in.
-}
column :
    SelectionSet decodesTo GithubNoFormat.Object.ProjectColumn
    -> SelectionSet decodesTo GithubNoFormat.Object.DeleteProjectCardPayload
column object____ =
    Object.selectionForCompositeField "column" [] object____ Basics.identity


{-| The deleted card ID.
-}
deletedCardId : SelectionSet GithubNoFormat.ScalarCodecs.Id GithubNoFormat.Object.DeleteProjectCardPayload
deletedCardId =
    Object.selectionForField "ScalarCodecs.Id" "deletedCardId" [] (GithubNoFormat.ScalarCodecs.codecs |> GithubNoFormat.Scalar.unwrapCodecs |> .codecId |> .decoder)
