-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.LicenseRule exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A description of the rule
-}
description : SelectionSet String GithubNoFormat.Object.LicenseRule
description =
    Object.selectionForField "String" "description" [] Decode.string


{-| The machine-readable rule key
-}
key : SelectionSet String GithubNoFormat.Object.LicenseRule
key =
    Object.selectionForField "String" "key" [] Decode.string


{-| The human-readable rule label
-}
label : SelectionSet String GithubNoFormat.Object.LicenseRule
label =
    Object.selectionForField "String" "label" [] Decode.string
