-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GithubNoFormat.Object.RemoveReactionPayload exposing (..)

import GithubNoFormat.InputObject
import GithubNoFormat.Interface
import GithubNoFormat.Object
import GithubNoFormat.Scalar
import GithubNoFormat.ScalarCodecs
import GithubNoFormat.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) GithubNoFormat.Object.RemoveReactionPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The reaction object.
-}
reaction :
    SelectionSet decodesTo GithubNoFormat.Object.Reaction
    -> SelectionSet decodesTo GithubNoFormat.Object.RemoveReactionPayload
reaction object____ =
    Object.selectionForCompositeField "reaction" [] object____ Basics.identity


{-| The reactable subject.
-}
subject :
    SelectionSet decodesTo GithubNoFormat.Interface.Reactable
    -> SelectionSet decodesTo GithubNoFormat.Object.RemoveReactionPayload
subject object____ =
    Object.selectionForCompositeField "subject" [] object____ Basics.identity
